---
- name: Excercise to configure machine via Ansible in AWS using CircleCli
  hosts: 3.84.159.166
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
    - setup