---
- name: Excercise to configure machine via Ansible in AWS using CircleCli
  hosts: ec2-3-85-99-9.compute-1.amazonaws.com
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
    - setup